<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DriverSeeder extends Seeder
{
    public function run(): void
    {
        $names = [
            "Guntur Sutrisno",
"Aris Marwanto",
"Yoga Kurniawan",
"Ismansyah",
"Belli Susika",
"Arief Budiono",
"Dedi Irawan",
"Aji Suranto",
"Mariyono",
"Novendra",
"Nur Haryanto",
"Rudi Heriyanto",
"Wantoni",
"Rudi Purwanto",
"Ridho Wahyudi",
"Rahmat Dede Kurniawan",
"Sarjan",
"Riyanto",
"Yalin",
"Arisdin",
"Dedi Kurniawan",
"Rudi Purnomo",
"Aditya Widiyanto",
"Iceh Hidayat",
"Martine M. Yusuf",
"Hepni Junian Sari",
"Wayan Bagus Arman Dane",
"Sugiyono",
"Santoso 2695",
"Aan Vitriadi",
"Endra Darmawan",
"Suherman",
"Asroni",
"Sarjiman",
"M. Teguh Imanto",
"Roni Santuri",
"Maman Sofian",
"M. Riyan Hariyadi",
"Retno Basuki",
"Yasser Yamael",
"Hadi Susanto",
"Sulaiman",
"Setiawan",
"Reza Putra Bella",
"Radianto Silaban",
"Erik Irawan",
"Tio Pratama",
"Panca Dwi Rianto",
"Hariyono",
"Ahmad Supriyadi",
"I Gede Made Hermanto",
"Jhon Feri Boy Saragih",
"Dadang Hermansyah",
"Ario Topan",
"Andri Kurniawan",
"Rico Ferdian",
"Junaidi",
"Abdul Basith",
"Agustiawan",
"Kamsari",
"Ricky Aldo",
"Bayu Riyadi",
"Musonip Adi Tiyan",
"Munandar Nopen Pramana",
"Agung Budiono",
"Ahmad Rizki Amalludin ",
"Junardi",
"Darfandi Syahputra",
"Sugiyatno",
"Agus Riyan Jaya",
"Asiman",
"Pujiyanto",
"Edi Purwanto",
"Iswan Setiawan",
"Iwan Setiawan",
"Agung Dwi Wicaksono",
"Hendri Siswanto",
"Kusmayadi",
"Jumadi",
"Tonny Ramadhan",
"Seno Wijaya",
"Rochman",
"Apriyadi",
"M. Farizal",
"Hendra Saputra",
"Pandi",
"M Rizal Saputra",
"Danar Winarto",
"Yusuf",
"Muchtarom",
"Yayan Handika Pratama",
"Yoyon Didik Wibowo",
"Andri Yansyah",
"Feris Handoko",
"Fitra Eri Gumantri",
"Chairul Hakim",
"Khairul Sidik",
"Dhony Kurniawan",
"Yudi Hartono",
"Dedi Hermaya",
"Waliadi",
"Aroni Wijaya",
"Iqbal Tri Ramadhan",
"Ronal Agus S",
"Sukirno",
"Ade Firmansyah",
"Jumeri",
"Murdani",
"Dedi Haryanto",
"Yansen Fadly",
"Syamsul Hidayat",
"Dirga Adi Wiratama",
"Andreas Silalahi",
"Aji Riswanto",
"Bayu Bastiyan Suherman ",
"M Rasid",
"Sugirin",
"Berry Noviawan",
"Sadam Husein",
"Hendrawan",
"Okta Farizal",
"Rifki Difo Al Bisma",
"Edi Mulyono",
"Tria Septa Kartika",
"Manik Sanjoyo",
"Gusmal Riyaldi",
"Yusuf Romadona",
"Firman Siahaan",
"Yeri Deptiawan",
"Roy Cahyanto",
"Napsi Musiyar",
"Siska Candra",
"Aditia",
"Sucipto",
"Muhammad Fadillah",
"Hajiji Julianto",
"Ari Budi Hartanto",
"Hajiono",
"Ridho Rizky Pratama",
"Dhimas Kukuh Prasetyo Adjie",
"Andi Santoso",
"Lukas Purwa Adiyatma S",
"Frans Wijaya Rachman",
"Idham Pramudianto",
"David Lugara",
"Eko Saputra  041",
"Gilang Fadillah Putra",
"Wahyudi 875",
"David Andrianto",
"Ferdy Nugraha",
"Beny Setiawan",
"Dedi Yanto",
"Teguh Santoso",
"Wahyudi",
"Senno Sahellano",
"Fitri Yandi",
"Firdaus Mustawan",
"Sando Royalno Farera",
"Kurniawan 24",
"Slamet Budi Anggoro",
"M. Kurniawan",
"Budi Setiawan",
"Kurniawan",
"Raden Zilfi Al Azis",
"Novika Darmawan",
"Aris Iswantoro",
"Anton Yapri",
"Ivan Noprianto",
"Tri Marliyanto",
"Dawam Ubaidi",
"Sutrisno",
"Agus Setiyono",
"Dodi Haryanto",
"Rico Ariyansyah",
"Irhamni",
"Hanu Iryan Pratama",
"Agus Feriyanto",
"Sugiyanto 2135",
"Riki Yakup Pajrin",
"Trinyoto'",
"Frendy Chrisyanto",
"Haekal Maulana",
"Indra Setiawan",
"Fariza Agung ",
"Agus Supriyatna",
"Anton Setiawan",
"Erwiyanto",
"Aspriyanto",
"Akhmad Rustandi",
"Hendra Yani",
"Ary Supriyadi",
"Rahmat Wahyudi",
"Frido Pratama",
"Choirul Muslim",
"Agung Nugroho",
"Hendro Jumianto",
"Didik Amanu",
"Muhammad Iqbal",
"Novi Indahwansyah",
"Amir Ma'Ruf",
"Samsul",
"Agus Suryana",
"Gun Gun Guntara",
"Hendrik",
"Krishadi Eko P",
"Kiki Romansyah",
"Suherman 867",
"Aris Joko Murtanto",
"Rudi Hartono",
"Roni Kurniawan",
"Raga Irlanda",
"Supriyadi",
"Feri Antoni",
"Okta Riansyah",
"Beni Handoko",
"Wahyu Wisnu Wardana",
"Adi Saputro Wibowo",
"Hariski Dwiyan Wicaksana",
"Windra Idris Afandi",
"Harianto",
"Budi Supriono",
"Ryan Aprilianata",
"Rian Iswadi",
"Jaeni",
"Najib Ridho Hartanto",
"Wijiyanto",
"Even",
"Opi Suryanto",
"Herman",
"Amin Sonhaji",
"Enal Kurniawan",
"Djumain",
"Ari Saputra",
"Rico Fan Istanto",
"Sulton Hidayatuloh",
"Muntolib",
"Ani Hermanto",
"Hariyanto 914",
"Sugiyanto",
"Toni Yus'An",
"Indarto Praidi",
"M Rendy Saputra",
"Alfian",
"Sofyan Nurkadri",
"Hary Elvinta",
"Sapta Pandita",
"Frendi Awan Aji",
"Eko Saputra",
"Suparjo",
"Diat Hendrik Guntoro",
"I Nengah Sumada",
"Mustofa",
"Aldi Zulkarnain",
"Rian Hidayat",
"Amin Nuryadi",
"Ruswan Karyanto",
"Muhammad Saddam ",
"Imron Syahroni",
"Yudis Wanto ",
"Falaq Santoso",
"Hegar Masrudi",
"Panji Krismayadi",
"Sunarto",
"Bukhori Muslim",
"Galang Priatama",
"Widodo",
"Agus Amin Syaifudin",
"Ponimin",
"Angga Stiawan",
"Khairul Anwar",
"Supyani",
"Aris Eka Saputra",
"Ismanto 921",
"Andi Apriyadi",
"Aan Purnomo",
"Firmansyah",
"Huldery",
"M. Safei",
"Danu Anggoro",
"Rika Muhamad Andrianto",
"Dovi Irwanto",
"Deny Kurniawan",
"Wagiyanto",
"Ahmad Zainudin",
"Husen Ngilmi",
"Eko Suwarto",
"Sri Susetio",
"Supriyana",
"Wahyu Pratama",
"Agus Setiawan",
"Sudarmadi",
"Riza Asmara",
"Riki Susanto",
"Suyudi",
"Rustam",
"Wikaldo ",
"Agung Wahyudi ",
"Imron Efendi",
"Eddy",
"Saiful Anwar",
"Ismail",
"Erwin Stia",
"Wahyudi Septianto",
"Prayogi Adi Nugroho",
"Mahadi Putra",
"Heru Santoso",
"Ferry Vebrian",
"Erwin Efendi",
"Indian Prima",
"Trio Pangestu",
"Muh Azis",
"Eko Ambar Yanto",
"Hermanto",
"Diendi Qomara Agusta",
"Iswanto",
"Winarto",
"Bambang Susanto",
"Fahri fitrian saputra",
"Joko Purnomo",
"Muhammad ilham",
"Frans Antonius Panjaitan",
"Hargo Yowono",
"Rizki Kurniawan",
"Wawan Setiawan",
"SUHENDRI",
"Andri Toni Saputra",
"Suherman_778",
"Desmi Nofrizal",
"Tukiman",
"Pariyanto",
"Paryono",
"Sopian Jamil",
"Dedi Suryadi",
"Hendra setiawan",
"Wahidin Harahap",
"Indra Kurniawan",
"Diki Nurcahyono",
"Suyandi",
"Ismanto",
"Hersandi",
"Andesta Agung",
"Riyon Riyadi",
"Muhamad Sainal Abidin",
"Boby Andrian Sinaga",
"Erwan Alek Pamungkas",
"Triono",
"Dimas Ronggo",
"M. Saleh",
"Purwanto",
"Febby Rizky Hardiansyah",
"Hendri Setiawan",
"Tedi Mardianto",
"Fitri Antoni",
"Ronali Subandi",
"Yoga Saputra ",
"Merlian Chandra",
"Taufiq Hidayat",
"Hestu Yurianto",
"Ridho Kurnia Sandi",
"CUTRI ALFASYA ARIEF",
"Agus Suyatno",
"Muhammad Putra Mulya",
"Rendra Rasuanto",
"Deni Kurniawan",
"Dedi Setiawan",
"Amir Junaidi",
"M Arif",
"Dimas Putrawan ",
"M. Sofiyan S.",
"Gunanto",
"Sanari",
"Aziz Maulana Putra",
"Fransiskus Cristovel Adinata Ambarita",
"Septera",
"Triyono",
"M. Ryan Gumai",
"Achmad Saudy",
"Kristian Ivanta Bangun",
"Ikhsan Awaluddin",
"Angga Prasetio",
"Dwi Saputro",
"Fajar Wahyu Tri Febrianto",
"Hadi Winarko",
"Sigit Prayoga",
"Medi Yanto",
"Tomi Fernando",
"Aji Rinaldi",
"Beni Eko Hariyanto",
"Dede Jafar",
"Viktor Kiki Renandi Setiawan ",
"Triman Saputra",
"Fahrizal",
"Heriyanto",
"Jupriono",
"Fatoni",
"Dede Sampurno ",
"Bimo Ardiyanto",
"Royani",
"M. Faizal ",
"Wisnu Hendrik",
"Eky Saputra",
"Andri Furqon",
"Sunaryo",
"Wahyu Aris Munandar",
"Rizal Sitorus ",
"Zulfikar Ferliansyah",
"Indra Tulamri",
        ];

        $data = [];

        foreach ($names as $index => $name) {
            $data[] = [
                'name' => trim($name),
                'phone_number' => $this->fakePhone($index),
                'address' => 'Jl. Raya Driver No. ' . ($index + 1) . ', Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('drivers')->insert($data);
    }

    private function fakePhone(int $i): string
    {
        // Konsisten, unik, format Indonesia
        return '08' . str_pad((string)(700000000 + $i), 9, '0', STR_PAD_LEFT);
    }
}
